# Generated by Django 3.1.1 on 2020-10-12 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0004_secondpagemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='secondpagemodel',
            old_name='title',
            new_name='name',
        ),
    ]
