# Generated by Django 3.1.1 on 2020-10-12 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0005_auto_20201012_2244'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SecondPageModel',
        ),
    ]
