# Generated by Django 3.1.1 on 2020-10-12 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0009_secondpagemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SecondPageModel',
        ),
    ]
