# Generated by Django 3.1.1 on 2020-10-13 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0012_thirdpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SecondPageModel',
        ),
        migrations.DeleteModel(
            name='Thirdpage',
        ),
    ]
