# Generated by Django 3.1.1 on 2020-10-13 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0013_auto_20201013_0340'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondPageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
    ]
